### PR TITLE
Fixes up implicit parameter lists

### PR DESCRIPTION
**Pull request by mdedetrich**
Zhewbacca didn't curry implicit parameter lists, its often idiomatic to curry implicit lists as thats what allows you to pass in in implicits automatically

Although this makes no difference for dependency injection for the typical way (using Guice), if you need to manually hardwire your `SecurityFilter` it makes it a lot easier since there are fewer parameters that you need to provide (in this case, `ExecutionContext` and `Materializer` can be skipped by marking them as implicit)

### CODE REVIEW

**Comment by lasomethingsomething** [comment]
@dmitrykrivaltsevich Hey Dmitry, any plan to review this PR and merge? It's been here for a while. cc @mdedetrich

**Comment by dmitrykrivaltsevich** [comment]
@LappleApple Hi Lauri, most likely this will happen during HackWeek

**Comment by lasomethingsomething** [comment]
@dmitrykrivaltsevich hmmm, looks like it didn't get merged. Now there's a conflict. @mdedetrich, what are your thoughts?

**Review by dmitrykrivaltsevich — CHANGES_REQUESTED** [review]
we need to increase version in build.sbt

**Comment by dmitrykrivaltsevich** [comment]
I'm closing this PR because it's stale.

**Pull request closed without merging**
